import { PERMISSIONS } from "./permissions";
import { Role } from "./roles";
import type { Permission } from "./permissions";

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  admin: [
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_STATION,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_FUEL_REQUEST,
    PERMISSIONS.APPROVE_FUEL_REQUEST,
    PERMISSIONS.CREATE_FUEL_REQUEST,
    PERMISSIONS.VIEW_STATION,
  ],

  driver: [
    PERMISSIONS.CREATE_FUEL_REQUEST,
    PERMISSIONS.VIEW_FUEL_REQUEST,
    PERMISSIONS.VIEW_STATION,
  ],

  station_staff: [
    PERMISSIONS.APPROVE_FUEL_REQUEST,
    PERMISSIONS.VIEW_FUEL_REQUEST,
    PERMISSIONS.VIEW_STATION,
  ],

  station_manager: [
    PERMISSIONS.MANAGE_STATION,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_FUEL_REQUEST,
    PERMISSIONS.APPROVE_FUEL_REQUEST,
    PERMISSIONS.VIEW_STATION,
  ],
};