services:

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: fuel-api

    restart: unless-stopped

    env_file:
      - .env.production

    ports:
      - "8080:8080"

    depends_on:
      - postgres


  postgres:
    image: postgres:16

    container_name: fuel-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fuel_system

    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:

  postgres_data: